[package]
name = "embedded-hal-mock"
version = "0.3.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
categories = ["embedded", "hardware-support", "development-tools::testing"]
description = "A collection of mocked devices that implement the embedded-hal traits"
documentation = "https://docs.rs/embedded-hal"
keywords = ["hal", "IO", "spi", "i2c"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dbrgn/embedded-hal-mock"
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[dependencies]
embedded-hal = { git = "https://github.com/rust-embedded/embedded-hal", branch = "master" }
